ae = "/app/flux/ae.safetensors"
apply_t5_attn_mask = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_l = "/app/flux/clip_l.safetensors"
discrete_flow_shift = 3.1582
dynamo_backend = "no"
epoch = 20  # Slightly increased from default
full_bf16 = true
gradient_accumulation_steps = 2  # Better for memory
gradient_checkpointing = true
guidance_scale = 1.0
highvram = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 4
max_timestep = 1000
max_train_steps = 2000  # Reasonable default
mem_eff_save = true
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 64  # Conservative value
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all", "train_t5xxl=True",]
network_dim = 128  # Balanced for quality/speed
network_module = "networks.lora_flux"
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "Adafactor"
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = "/app/flux/unet.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 10
save_model_as = "safetensors"
save_precision = "float"
seed = 42
t5xxl = "/app/flux/t5xxl_fp16.safetensors"
t5xxl_max_token_length = 512
text_encoder_lr = [ 2e-5, 2e-5,]  # Slightly reduced
timestep_sampling = "sigmoid"
train_batch_size = 2
train_data_dir = ""
unet_lr = 5e-5  # Conservative learning rate
vae_batch_size = 4
wandb_run_name = "last"
xformers = true

max_grad_norm = 1.0
warmup_steps = 100