bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
clip_skip = 1
epoch = 20  # Slightly increased
enable_bucket = true
gradient_accumulation_steps = 2  # Better memory usage
gradient_checkpointing = true
huggingface_path_in_repo = "checkpoint"
huggingface_repo_id = ""
huggingface_repo_type = "model"
huggingface_repo_visibility = "public"
huggingface_token = ""
keep_tokens = 0
learning_rate = 5e-5  # Conservative rate
logging_dir = "/app/outputs/logs"
lr_scheduler = "cosine"
lr_scheduler_num_cycles = 1
lr_warmup_steps = 100
max_bucket_reso = 2048
max_data_loader_n_workers = 4
max_token_length = 150
max_train_steps = 2000  # Reasonable default
min_bucket_reso = 256
mixed_precision = "bf16"
network_alpha = 64  # Balanced
network_args = []
network_dim = 128  # Good balance
network_module = "networks.lora"
noise_offset = 0.0
optimizer_args = ["weight_decay=0.01", "betas=[0.9,0.999]"]
optimizer_type = "AdamW8bit"
output_dir = "/app/outputs"
output_name = "last"
pretrained_model_name_or_path = ""
prior_loss_weight = 1.0
resolution = "1024,1024"
resume = ""
sample_every_n_epochs = 10
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 10
save_model_as = "safetensors"
save_precision = "float"
seed = 42
shuffle_caption = false
text_encoder_lr = 2e-5  # Slightly reduced
train_batch_size = 2
train_data_dir = ""
train_text_encoder = false
unet_lr = 5e-5  # Conservative rate
vae_batch_size = 4
v_parameterization = false
v_pred_like_loss = 0
wandb_api_key = ""
xformers = true
min_snr_gamma = 5
max_grad_norm = 1.0